definitions:
  model.R:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: zzhang_xz@163.com
    name: alice52
    url: https://github.com/alice52/tools
  description: This is a crypto server by golang.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/alice52
  title: Swagger Crypto API
  version: "1.0"
paths:
  /decrypt:
    get:
      consumes:
      - application/json
      description: Decrypts a value using Jasypt
      parameters:
      - description: Jasypt encryption key
        in: query
        name: key
        type: string
      - description: Value to decrypt
        in: query
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.R'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.R'
      summary: Decrypt a value
      tags:
      - Crypto
  /encrypt:
    get:
      consumes:
      - application/json
      description: Encrypts a value using Jasypt
      parameters:
      - description: Jasypt encryption key
        in: query
        name: key
        type: string
      - description: Value to encrypt
        in: query
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.R'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.R'
      summary: Encrypt a value
      tags:
      - Crypto
swagger: "2.0"
