version: '3.0'
services:
  project-worklow:
    image: registry.cn-shanghai.aliyuncs.com/alice52/tools-tool-encrypt:20221031.e507fe0
    restart: 'on-failure:3'
    container_name: dev-tool-encrypt
    volumes:
      - /root/project-name/logs:/log
    ports:
      - 8010:8080
    environment:
      - TZ=Asia/Shanghai
      # - spring.profiles.active=cloud
