version: '3.0'
services:

  dev-tool-generator:
    image: registry.cn-shanghai.aliyuncs.com/alice52/tools-tool-generator:20221031.4b2c7ce
    restart: 'on-failure:3'
    container_name: dev-tool-generator
    volumes:
      - /root/dev-tool-generator/logs:/logs
    ports:
      - 8010:8080
    environment:
      - TZ=Asia/Shanghai

  common-tool-encrypt:
    image: registry.cn-shanghai.aliyuncs.com/alice52/j-tools-tool-encrypt-jdk17:20231205.c4ec740
    restart: 'always'
    container_name: dev-common-tool-encrypt
    environment:
      JAVA_OPTS: "-Xms256m -Xmx256m"
      TZ: Asia/Shanghai
    ports:
      - 8080:8080

  common-tool-encrypt-go:
    image: registry.cn-shanghai.aliyuncs.com/alice52/g-tools-tool-encrypt-go1.20.x:20231222.4f85ee2
    restart: 'always'
    container_name: dev-common-tool-encrypt-go
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8088:8080
