server:
  port: 8080

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

# Spring 相关
spring:
  mvc:
    async:
      request-timeout: 20
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null